---
- name: Ensure basic apt packages are installed on system
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - bzip2
      - curl
      - dnsutils
      - dstat
      - etckeeper
      - ffmpeg
      - git
      - golang-go
      - golang-src
      - htop
      - iftop
      - imagemagick
      - info
      - iotop
      - iperf
      - iptables
      - iptraf-ng
      - iputils-tracepath
      - locate
      - lshw
      - lsof
      - mtr
      - net-tools
      - nethogs
      - nload
      - nmap
      - openssh-client
      - pandoc
      - plocate
      - python3
      - python3-dev
      - python3-venv
      - screen
      - sysstat
      - systemd-timesyncd
      - tcpdump
      - tmux
      - traceroute
      - tree
      - ufw
      - unzip
      - vim
      - wget
      - whois
      - xz-utils
      - zip
    state: present
    update_cache: true

- name: Update apt cache and upgrade installed packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    state: present
