---
- name: Ensure the localhost vimrc file is present with specific contents
  ansible.builtin.copy:
    dest: /home/superadmin/.vimrc
    content: |
      syntax on
      set background=dark
      colorscheme ron
    owner: superadmin
    group: superadmin
    mode: '0644'
