---
- name: Ensure the /root/.vimrc file is present with specific contents
  become: true
  ansible.builtin.copy:
    dest: /root/.vimrc
    content: |
      syntax on
      set background=dark
      colorscheme ron
    owner: root
    group: root
    mode: '0644'
